// Package analytics implements a high-throughput, append-only event tracking system
// for the Forge platform. It ingests events via a buffered channel for zero-latency
// HTTP responses and flushes them to daily rotated JSONL logs on disk.
package analytics

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/ayushkunwarsingh/forge/config"
	"github.com/ayushkunwarsingh/forge/logger"
)

// Event represents a single tracked action in the analytics engine.
type Event struct {
	// ID is a unique UUID generated by the client or randomly assigned.
	ID string `json:"id"`
	// Name is the event name (e.g., "page_view", "button_click", "signup").
	Name string `json:"name"`
	// Timestamp is the UTC time the event occurred.
	Timestamp time.Time `json:"timestamp"`
	// UserID is the authenticated user's ID, if any.
	UserID string `json:"user_id,omitempty"`
	// SessionID is an anonymous session identifier to string events together.
	SessionID string `json:"session_id,omitempty"`
	// Properties contains arbitrary event metadata (e.g., {"plan": "pro"}).
	Properties map[string]interface{} `json:"properties,omitempty"`
	// Context contains device/network info automatically collected by the server.
	Context EventContext `json:"context"`
}

// EventContext holds automatically collected request metadata.
type EventContext struct {
	IP        string `json:"ip,omitempty"`
	UserAgent string `json:"user_agent,omitempty"`
	Referrer  string `json:"referrer,omitempty"`
	URL       string `json:"url,omitempty"`
}

// Engine manages the ingestion buffer and disk flusher.
type Engine struct {
	cfg       *config.Config
	log       *logger.Logger
	eventsDir string

	// buffer is the async ingestion channel
	buffer chan Event
	// flushInterval dictates how often batch writes happen
	flushInterval time.Duration

	// shutdown signals the flusher to write remaining events and exit
	shutdown chan struct{}
	wg       sync.WaitGroup

	// File tracking
	currentDate time.Time
	currentFile *os.File
	mu          sync.Mutex // Protects file operations
}

// NewEngine creates and starts a new Analytics Engine.
func NewEngine(cfg *config.Config, log *logger.Logger) (*Engine, error) {
	eventsDir := cfg.ResolveDataPath("analytics", "events")
	if err := os.MkdirAll(eventsDir, 0755); err != nil {
		return nil, fmt.Errorf("analytics: failed to create events directory: %w", err)
	}

	flushInterval, err := time.ParseDuration(cfg.Analytics.FlushInterval)
	if err != nil {
		flushInterval = 5 * time.Second
	}

	bufferSize := cfg.Analytics.BufferSize
	if bufferSize <= 0 {
		bufferSize = 10000
	}

	eng := &Engine{
		cfg:           cfg,
		log:           log,
		eventsDir:     eventsDir,
		buffer:        make(chan Event, bufferSize),
		flushInterval: flushInterval,
		shutdown:      make(chan struct{}),
	}

	eng.wg.Add(1)
	go eng.flusher()

	log.Info("Analytics engine started", logger.Fields{
		"buffer_size":    bufferSize,
		"flush_interval": flushInterval.String(),
	})

	return eng, nil
}

// Track queues a new event for disk persistence.
// It is non-blocking up to the configured BufferSize.
func (e *Engine) Track(event Event) error {
	if event.Timestamp.IsZero() {
		event.Timestamp = time.Now().UTC()
	}

	select {
	case e.buffer <- event:
		return nil
	default:
		// Buffer is full — drop the event to prevent crashing the server
		e.log.Warn("Analytics buffer full, dropping event", logger.Fields{
			"event_name": event.Name,
		})
		return fmt.Errorf("analytics: ingestion buffer is full")
	}
}

// flusher runs in the background, writing events to disk in batches.
func (e *Engine) flusher() {
	defer e.wg.Done()

	ticker := time.NewTicker(e.flushInterval)
	defer ticker.Stop()

	// retentionTicker runs once a day to clean up old logs
	retentionTicker := time.NewTicker(24 * time.Hour)
	defer retentionTicker.Stop()

	var batch []Event

	for {
		select {
		case event := <-e.buffer:
			batch = append(batch, event)

			// If batch gets too large, force flush
			if len(batch) >= 1000 {
				e.flushBatch(batch)
				batch = batch[:0]
			}

		case <-ticker.C:
			if len(batch) > 0 {
				e.flushBatch(batch)
				batch = batch[:0]
			}

		case <-retentionTicker.C:
			e.cleanupOldLogs()

		case <-e.shutdown:
			// Drain remaining events
			for len(e.buffer) > 0 {
				batch = append(batch, <-e.buffer)
			}
			if len(batch) > 0 {
				e.flushBatch(batch)
			}
			e.closeCurrentFile()
			return
		}
	}
}

// flushBatch writes a slice of events to the current daily log file.
func (e *Engine) flushBatch(batch []Event) {
	e.mu.Lock()
	defer e.mu.Unlock()

	now := time.Now().UTC()

	// Check if we need to rotate logs (day changed)
	if e.currentFile == nil || now.YearDay() != e.currentDate.YearDay() || now.Year() != e.currentDate.Year() {
		e.rotateFile(now)
	}

	if e.currentFile == nil {
		e.log.Error("Analytics flusher failed", logger.Fields{"error": "no open log file"})
		return
	}

	// Write events as JSON lines (JSONL)
	for _, event := range batch {
		data, err := json.Marshal(event)
		if err != nil {
			continue // skip broken events
		}

		// Append newline
		data = append(data, '\n')

		if _, err := e.currentFile.Write(data); err != nil {
			e.log.Error("Failed to write analytics event", logger.Fields{"error": err.Error()})
		}
	}

	// Sync to disk to ensure durability against power loss
	if err := e.currentFile.Sync(); err != nil {
		e.log.Warn("Failed to sync analytics log", logger.Fields{"error": err.Error()})
	}
}

// rotateFile closes the current log file and opens a new one for today.
func (e *Engine) rotateFile(now time.Time) {
	if e.currentFile != nil {
		e.currentFile.Close()
	}

	// "2026-04-19.jsonl"
	filename := fmt.Sprintf("%04d-%02d-%02d.jsonl", now.Year(), now.Month(), now.Day())
	path := filepath.Join(e.eventsDir, filename)

	// Open in append-only mode, create if missing
	file, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		e.log.Error("Failed to open analytics log file", logger.Fields{
			"path":  path,
			"error": err.Error(),
		})
		e.currentFile = nil
		return
	}

	e.currentFile = file
	e.currentDate = now
}

// closeCurrentFile safely closes the active log.
func (e *Engine) closeCurrentFile() {
	e.mu.Lock()
	defer e.mu.Unlock()
	if e.currentFile != nil {
		e.currentFile.Close()
		e.currentFile = nil
	}
}

// Shutdown gracefully stops the engine, waiting for all buffers to flush.
func (e *Engine) Shutdown() {
	e.log.Info("Shutting down analytics engine...")
	close(e.shutdown)
	e.wg.Wait()
	e.log.Info("Analytics engine stopped cleanly")
}

// cleanupOldLogs removes logs older than RetentionDays.
func (e *Engine) cleanupOldLogs() {
	retention := e.cfg.Analytics.RetentionDays
	if retention <= 0 {
		return // 0 = keep forever
	}

	cutoff := time.Now().AddDate(0, 0, -retention)

	entries, err := os.ReadDir(e.eventsDir)
	if err != nil {
		e.log.Warn("Failed to read analytics directory for cleanup", logger.Fields{"error": err.Error()})
		return
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".jsonl") {
			continue
		}

		info, err := entry.Info()
		if err != nil {
			continue
		}

		if info.ModTime().Before(cutoff) {
			path := filepath.Join(e.eventsDir, entry.Name())
			if err := os.Remove(path); err != nil {
				e.log.Warn("Failed to delete old analytics log", logger.Fields{
					"file":  entry.Name(),
					"error": err.Error(),
				})
			} else {
				e.log.Info("Deleted old analytics log", logger.Fields{"file": entry.Name()})
			}
		}
	}
}
